import React, { useEffect, useState } from 'react'
import Detail from '../../../Components/Detail'
import Navbar from '../../../Components/Navbar'
import Head from 'next/head'
import Script from 'next/script'
import { useRouter } from 'next/router'
import Footer from '../../../Components/Footer'
import axios from 'axios'
export default function  PackageDetails ()  {
  const router = useRouter()
  let packageName = router.query.name
  const [singlePackage, setPackage] = useState()
  const [packageDays,setPackageDays] = useState()
  const [packageFAQ,setPackageFAQ] = useState();
  const [semiNav,setSemiNav] = useState("detailnav")


  const getPackage = async () => {
    const response = await axios.get(
      'http://127.0.0.1:8000/package/' + packageName,
    )
    if(packageName !== undefined){
      setPackage(response.data[0])
      const daysResponse = await axios.get(
        `http://127.0.0.1:8000/day-details/${response.data[0].id}`,
      )
      setPackageDays(daysResponse.data)

      const FAQresponse = await axios.get(
        `http://127.0.0.1:8000/FAQ/${response.data[0].id}`,
      )
      setPackageFAQ(FAQresponse.data)
    }
  }

  useEffect(() => {
    getPackage();
  }, [packageName])

  useEffect(() => {
    const options = { passive: true }; // options must match add/remove event
    const scroll = (event) => {
      const { pageYOffset, scrollY } = window;
      console.log("yOffset", pageYOffset, "scrollY", scrollY);
      if(pageYOffset>=500) setSemiNav('semiNavTop')
      else setSemiNav('')
    };
    document.addEventListener("scroll", scroll, options);
    // remove event on unmount to prevent a memory leak
    () => document.removeEventListener("scroll", scroll, options);
  }, []);

  return (
    <>
      <Head>
        <title>Travel Nepal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        async
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        defer
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Navbar />
      <div id="content" className="site-content">
        <div
          className="new"
          style={{
            backgroundImage: `url('http://127.0.0.1:8000${singlePackage?.image}') `,
            minHeight: '500px',
            position: 'relative',
          
            backgroundSize: 'cover',
            backgroundRepeat: 'no-repeat',
            backgroundPosition: 'center',
            zIndex: '-1',

          }}
        >
          <div className="hero-interior__content">
            <div className="container ">
              <h1 className="hero-interior__title ">{singlePackage?.name}</h1>
              <div className="hero-interior__meta">
                <span>
                  <div className="bi bi-geo-alt-fill"></div>
                  Nepal
                </span>
                <span>
                  <div className="bi bi-brightness-high-fill"></div>
                  {singlePackage?.days + ' Days'}
                </span>
                <span>
                  <div className="bi bi-moon-stars-fill"></div>
                  {singlePackage?.days-1 + ' Nights'}
                  
                </span>
              </div>
            </div>
          </div>
          <div className="quick-contact"></div>
        </div>
        <nav class={`container semiNavFixed scrollspy mt-4`}>
          <div className="row">
            <div className={`col-md-8 shadow ${semiNav}`}>
              <ul className="m-0 p-0 d-flex flex-wrap justifly-content-center align-items-center">
                <li class="">
                  <a href="#overview">Overview</a>
                </li>
                <li class="">
                  <a href="#itinerary">Your Itinerary</a>
                </li>
                <li class="">
                  <a href="#info">Additional Info</a>
                </li>
                <li class="">
                  <a href="#faq">FAQ</a>
                </li>
                <li class="">
                  <a href="#included">What To Expect</a>
                </li>
         
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <Detail 
        singlePackage = {singlePackage}
        packageDays = {packageDays}
        FAQ = {packageFAQ}
        key = {singlePackage?.id}
      />
      <Footer></Footer>
    </>
  )
}

