import React from 'react';
import Navbar from "../Components/Navbar";
import Head from 'next/head';
import Script from 'next/script';
import Instagram from "../Components/Instagram"
import Footer from "../Components/Footer"
const contact = () => {
    return (
        <>
            <Head>
                <title>Travel Nepal</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
                    rel="stylesheet"
                    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
                    crossorigin="anonymous"
                ></link>
            </Head>
            <Script
                id="my_script"
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                async
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"
            ></Script>
            <Script
                id="my_script"
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                defer
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"
            ></Script>
            <Navbar />
            <div className="">
                <div className="inner-banner-section">
                    <img src="/image/inner-banner-vctr.png" className="inner-banner-vector" alt="image" />
                    <div className="container">
                        <div className="row justify-content-center">
                            <div className="col-md-8">
                                <div className="breadcrumb-area">
                                    <span>Get in Touch</span>
                                    <h2>Let’s Have A Talk Together</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="info-section pt-120 pb-120">
                <div className="container">
                    <div className="row  justify-content-center">
                        <div className="col-lg-7 col-md-10 col-sm-12">
                            <div className="info-title-area">
                                <h3>Astrip Travel Agency Inc.</h3>
                                <p>
                                    But I must explain to you how all this mistaken idea of denouncing
                                    pleasure and praising pain was born and I will give you a complete
                                    account of the system, and expound the actual teachings of the great
                                    explorer of the truth, the master-builder of human happiness.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div className=" d-flex gap-2 flex-wrap justify-content-center">
                        <div className="col-lg-3 col-md-6 col-sm-10">
                            <div className="info-single">
                                <div className="info-icon">
                                    <i class="bi bi-geo-alt fw-bold"></i>
                                </div>
                                <div className="info-text">
                                    <h3>Address</h3>
                                    <p>168/170, Ave 01, Dhaka</p>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6 col-sm-10">
                            <div className="info-single">
                                <div className="info-icon">
                                    <i class="bi bi-telephone"></i>
                                </div>
                                <div className="info-text">
                                    <h3>Call Us!</h3>
                                    <a href="tel:+8801569862560">+88 0156 986 2560</a>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-6 col-sm-10">
                            <div className="info-single">
                                <div className="info-icon">
                                    <i class="bi bi-envelope"></i>
                                </div>
                                <div className="info-text">
                                    <h3>Email Info</h3>
                                    <a href="mailto:info@companyname123.com">info@companyname123.com</a>
                                </div>
                            </div>
                        </div>
                        <div className="container mt-5">
                            <div className="mapouter">
                                <div className="gmap_canvas">
                                    <iframe
                                        className="gmap_iframe"
                                        frameBorder={0}
                                        scrolling="no"
                                        marginHeight={0}
                                        marginWidth={0}
                                        src="https://maps.google.com/maps?width=1250&height=400&hl=en&q=Anam nagar&t=&z=14&ie=UTF8&iwloc=B&output=embed"
                                    />
                                    <a href="https://mcpenation.com/">https://mcpenation.com</a>
                                </div>
                                <style
                                    dangerouslySetInnerHTML={{
                                        __html:
                                            ".mapouter{position:relative;text-align:right;width:1250px;height:400px;}.gmap_canvas {overflow:hidden;background:none!important;width:1250px;height:400px;}.gmap_iframe {width:1250px!important;height:400px!important;}"
                                    }}
                                />
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <div className="contact-section">
                <div className="contentTop text-center py-5">
                    <p style={{ color: '#82b440', fontSize: '1.4rem' }}>RESERVATION FORM</p>
                    <h1 className='fw-bolder'>Let’s Get in Touch</h1>
                    <img src="/image/section-title-vector.svg" alt="" />
                </div>
                <div className="row d-flex justify-content-center">
                    <div className="col-12 col-md-10 col-sm-6">
                        <div className="contact-from-wrapper">
                            <form >
                                <div className="row">
                                    <div className="col-lg-6">
                                        <div className="form-inner">
                                            <input type="text" placeholder="Your Name:" />
                                        </div>
                                    </div>
                                    <div className="col-lg-6">
                                        <div className="form-inner">
                                            <input type="text" placeholder="Your Phone Number:" />
                                        </div>
                                    </div>
                                    <div className="col-lg-12">
                                        <div className="form-inner">
                                            <input type="text" placeholder="Type Your Subject:" />
                                        </div>
                                    </div>
                                    <div className="col-lg-12">
                                        <div className="form-inner">
                                            <textarea
                                                name="message"
                                                rows={5}
                                                placeholder="Type Your Message..."
                                                defaultValue={""}
                                            />
                                        </div>
                                    </div>
                                    <div className="col-lg-12 my-5">
                                        <div className='discoverButton'>
                                            <button><label>Submit Now</label></button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <Instagram />
            <Footer />
        </>
    )
}

export default contact