import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../Components/Navbar'
import MainHome from '../Components/MainHome'
import Search from '../Components/Search'
import Types from '../Components/Types'
import Destination from '../Components/Destination'
import Sticky from '../Components/Sticky'
import Package from '../Components/PopularPackages'
import Ask from '../Components/Ask'
import Success from '../Components/Success'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <MainHome />
      <Search />
      <Types />
      <Package />
      <Destination />
      <Sticky />
      <Ask />
      <Success />
    </div>
  )
}
