import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../Components/Navbar'
import IndexHome from '../Components/IndexHome'

import Collection from '../Components/Collection'

import PopularPackages from '../Components/PopularPackages'
import Feature from '../Components/Feature'
import Footer from '../Components/Footer'
import Search from '../Components/Search'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Search />
    </div>
  )
}
