import React from 'react'
import Detail from '../Components/Detail'
import Navbar from '../Components/Navbar'
import Head from 'next/head'
import Script from 'next/script'
function packageDetails() {
  return (
    <>
      <Head>
        <title>Travel Nepal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        async
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
        <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        defer
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
    <Navbar/>
      <div id="content" className="site-content">
        <div
          className="hero-interior"
          style={{
            background:
              'url(https://www.myeveresttrip.com/wp-content/uploads/2018/09/My-Everest-Trip-Everest-Base-Camp-Trek--1900x435.jpeg) no-repeat center center',
            backgroundSize: 'cover',
          }}
        >
          <div className="hero-interior__content">
            <div className="container ">
              <h1 className="hero-interior__title ">Everest Base Camp Trek</h1>
              <div className="hero-interior__meta">
                <span>
                  <svg className="icon icon-destination" aria-hidden="true">
                    <use
                      xlinkHref="https://www.myeveresttrip.com/wp-content/themes/lds_travel/assets/images/symbol-defs.svg#icon-destination"
                      x={0}
                      y={0}
                    />
                  </svg>
                  Nepal
                </span>
                <span>
                  <svg className="icon icon-day" aria-hidden="true">
                    <use
                      xlinkHref="https://www.myeveresttrip.com/wp-content/themes/lds_travel/assets/images/symbol-defs.svg#icon-day"
                      x={0}
                      y={0}
                    />
                  </svg>
                  14 Days
                </span>
                <span>
                  <svg className="icon icon-night" aria-hidden="true">
                    <use
                      xlinkHref="https://www.myeveresttrip.com/wp-content/themes/lds_travel/assets/images/symbol-defs.svg#icon-night"
                      x={0}
                      y={0}
                    />
                  </svg>
                  13 Nights
                </span>
              </div>
            </div>
          </div>
          <div className="quick-contact">
            
          </div>
        </div>
      </div>
      <Detail />
    </>
  )
}

export default packageDetails
