import React from 'react'
import Detail from '../Components/Detail'
import Navbar from '../Components/Navbar'
import Head from 'next/head'
import Script from 'next/script'
function packageDetails() {
  return (
    <>
      <Head>
        <title>Travel Nepal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        async
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        defer
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Navbar />
      <div id="content" className="site-content">
        <div
          className="hero-interior"
          style={{
            background: "url('/image/mountain.jpg' ) ",
            backgroundSize: 'cover',
            objectFit: 'cover',
            backgroundPosition: 'center',
          }}
        >
          <div className="hero-interior__content">
            <div className="container ">
              <h1 className="hero-interior__title ">Everest Base Camp Trek</h1>
              <div className="hero-interior__meta">
                <span>
                  <div className="bi bi-geo-alt-fill"></div>
                  Nepal
                </span>
                <span>
                  <div className="bi bi-brightness-high-fill"></div>
                  14 Days
                </span>
                <span>
                  <div className="bi bi-moon-stars-fill"></div>
                  13 Nights
                </span>
              </div>
            </div>
          </div>
          <div className="quick-contact"></div>
        </div>
        <nav class="container scrollspy mt-4">
          <div className="row">
            <div className="col-md-8 shadow">
              <ul className="m-0 p-0 d-flex flex-wrap justifly-content-center align-items-center">
                <li class="">
                  <a href="#overview">Overview</a>
                </li>
                <li class="">
                  <a href="#itinerary">Your Itinerary</a>
                </li>
                <li class="">
                  <a href="#trip-additional-info">Additional Info</a>
                </li>
                <li class="">
                  <a href="#why-us">Why US</a>
                </li>
                <li class="">
                  <a href="#trip-faq">FAQ</a>
                </li>
                <li class="">
                  <a href="#trip-map">Map</a>
                </li>{' '}
                <li class="">
                  <a href="#includes">What To Expect</a>
                </li>
                <li class="">
                  <a href="#fixed-dates">Cost &amp; Dates</a>
                </li>
                
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <Detail />
    </>
  )
}

export default packageDetails
