import React from 'react'
import Head from 'next/head'
import Script from 'next/script'
import Instagram from '../../../Components/Instagram'
import Footer from '../../../Components/Footer'

import { useEffect, useState } from 'react'
import axios from 'axios'
import Link from 'next/link'
import Navbar from '../../../Components/Navbar'
import { useRouter } from 'next/router'

function index() {
  const router = useRouter()
  let category = router.query.name
  const [packages, setPackages] = useState([])
  const getPackage = async () => {
    const response = await axios.get('http://127.0.0.1:8000/')
    setPackages(response.data)
  }

  var included = ''
  var includedArray

  useEffect(() => {
    getPackage()
  }, [])

  return (
    <>
      <Head>
        <title>Travel Nepal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        async
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        defer
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Navbar></Navbar>
      <div class="inner-banner-section">
        <img
          src="/image/inner-banner-vctr.png"
          class="inner-banner-vector"
          alt="image"
        />
        <div class="container ">
          <div class="row justify-content-center">
            <div class="col-md-8">
              <div class="breadcrumb-area">
                <span>Travel / Life Style</span>
                <h2>What To Know Before You Travel Plan A Trip.</h2>
                <div class="review-area">
                  <ul class="breadcrumb-meta-list">
                    <li> May 6, 2022</li>
                    <li>Victor Thornton</li>
                    <li> Comments: 02</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container">
        <div className="container px-5 mt-5">
          <div className="row justify-content-center g-4">
            {packages.map( res =>  {

              if(res.category === category)  {
              included = res.package_included
              includedArray = included.split(',').slice(0, 3)

              return (
                <>
                  <div className={`col-md-4 col-sm-8 best-plan`}>
                    <div className="best-plan-single1">
                      <div
                        className="image"
                        style={{
                          backgroundImage: `url(http://127.0.0.1:8000/${res.image})`,
                          height: '30vh',
                          backgroundSize: 'cover',
                          backgroundPosition: 'center',
                        }}
                      ></div>

                      <div class="content">
                        <p>{`From $ ${res.category}`}</p>
                        <h4>
                          <a href="/tour-package-details">
                            {res.name}
                          </a>
                        </h4>
                        <div class="best-plan-meta">
                          <span class="duration">
                            <i class="bi bi-clock"></i>
                            {`${res.days} days ${
                              res.days - 1
                            } night`}
                          </span>
                          <span class="rating">
                            <i class="bi bi-star-fill"></i>4.8 (150)
                          </span>
                        </div>
                        <div class="list-area">
                          <h5>Free Package Facility:</h5>
                          <ul class="plan-list1">
                            {includedArray.map((element) => {
                              return <li>{element}</li>
                            })}
                          </ul>
                        </div>

                        <div className="discoverButtonReverse">
                          <Link href={`/package/${res.name}`}>
                            <label>Explore More</label>
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </> 
              )}
            })}
          </div>
        </div>
      </div>

      <Instagram></Instagram>
      <Footer></Footer>
    </> 
  )
}

export default index
