import React, { useEffect, useState } from 'react'
import Detail from '../../../Components/Detail'
import Navbar from '../../../Components/Navbar'
import Head from 'next/head'
import Script from 'next/script'
import { useRouter } from 'next/router'
import axios from 'axios'
import Instagram from '../../../Components/Instagram'
import Footer from '../../../Components/Footer'

function blog() {
  return (
    <>
      <Head>
        <title>Travel Nepal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </Head>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        async
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Script
        id="my_script"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        defer
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Navbar></Navbar>

      <div class="inner-banner-section">
        <img
          src="/image/inner-banner-vctr.png"
          class="inner-banner-vector"
          alt="image"
        />
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-8">
              <div class="breadcrumb-area">
                <span>Travel / Life Style</span>
                <h2>What To Know Before You Travel Plan A Trip.</h2>
                <div class="review-area">
                  <ul class="breadcrumb-meta-list">
                    <li> May 6, 2022</li>
                    <li>Victor Thornton</li>
                    <li> Comments: 02</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="container mt-5">
        <div className="row">
          <div className="col-lg-8 pe-lg-3">
            <div className="blog-detail-single">
              <div class="blog-details-single">
                <img
                  src="/image/blog-details-image.png"
                  class="img-fluid"
                  alt="image"
                />
                <p>
                  At nearly one million acres, Olympic National Park is one of
                  the largest national parks in the lower 48 and is home to a
                  wide range of biodiverse ecosystems. From the moss-l aden Hoh
                  Rainforest to the psychedelic tide pools of Rialto Beach and
                  the far-flung glaciated peaks that hug the skyline, choosing
                  just one place to hang your hat at the end of the day can feel
                  overwhelming.
                </p>
                <p>
                  This is all good for beginners but when these blogs grow, most
                  bloggers forgot about design and instead doubled down on SEO
                  and m arketing.{' '}
                </p>
                <blockquote>
                  <h4>
                    There is a way out of every box, a solution to every puzzle
                    it’s just a matter of fin ding it.
                  </h4>
                  <div class="quote-icon">
                    <svg
                      width="32"
                      height="30"
                      viewBox="0 0 32 30"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M8.35 0.237864C8.25703 0.344114 6.50391 2.54216 4.45195 5.12536C1.49688 8.8574 0.726562 9.87341 0.726562 10.0195C0.726562 10.1789 0.826172 10.2918 1.3043 10.6902C1.62969 10.9492 2.30703 11.5933 2.81836 12.1047C4.89023 14.1965 6.10547 16.2418 6.53047 18.3336C6.66992 18.9976 6.66992 20.3058 6.53047 21.116C6.11875 23.5465 4.50508 26.4617 2.24063 28.8789C1.86211 29.2773 1.72266 29.4765 1.72266 29.6027C1.72266 30.0344 2.02813 30.041 3.01094 29.6293C5.8 28.4539 8.60234 26.5879 10.6543 24.5293C13.3105 21.873 14.8645 18.9644 15.5086 15.4648C15.6945 14.4754 15.6813 12.5961 15.482 11.6265C14.7184 7.85466 12.6 3.97654 9.55859 0.769114C8.80156 -0.0277615 8.65547 -0.0875263 8.35 0.237864Z"></path>
                      <path d="M23.9555 0.237936C23.8625 0.344187 22.1094 2.54223 20.0574 5.12543C17.1023 8.85747 16.332 9.87348 16.332 10.0196C16.332 10.1789 16.4316 10.2918 16.9164 10.6903C17.2352 10.9493 17.9125 11.5934 18.4238 12.1047C20.4957 14.1965 21.7109 16.2418 22.1359 18.3336C22.2754 18.9977 22.2754 20.3059 22.1359 21.1161C22.0098 21.8399 21.6711 22.9555 21.3125 23.7789C20.6152 25.386 19.2074 27.4446 17.7598 28.9719C17.4543 29.2973 17.3281 29.4832 17.3281 29.6094C17.3281 30.0344 17.6336 30.0411 18.6164 29.6293C22.0629 28.1817 25.5293 25.645 27.6344 23.0352C29.1617 21.1426 30.3238 18.8383 30.8684 16.627C31.1672 15.4184 31.2336 14.8672 31.2336 13.5723C31.2336 12.45 31.2203 12.2176 31.0543 11.4739C30.2508 7.71528 28.1723 3.93676 25.1641 0.769186C24.407 -0.027689 24.2609 -0.0874538 23.9555 0.237936Z"></path>
                    </svg>
                  </div>
                </blockquote>
                <h3 class="blog-details-subtitle">
                  Why You Shouldn’t Ride Elephants France.
                </h3>
                <p>
                  geism in the web development field is certainly out there.
                  Though it needn’t prevent you from embarking on an
                  intellectually rewarding (and well-paid) career path! A
                  willingness to learn, and some creative thinking to tie in
                  your past experience goes a long way.
                </p>
                <div class="row details-img-group g-4">
                  <div class="col-lg-4 col-md-4 col-sm-12">
                    <img
                      src="/image/blog-details-img2.png"
                      class="img-fluid"
                      alt="image"
                    />
                  </div>
                  <div class="col-lg-4 col-md-4 col-sm-12">
                    <img
                      src="/image/blog-details-img3.png"
                      class="img-fluid"
                      alt="image"
                    />
                  </div>
                  <div class="col-lg-4 col-md-4 col-sm-12">
                    <img
                      src="/image/blog-details-img4.png"
                      class="img-fluid"
                      alt="image"
                    />
                  </div>
                </div>
                <p>
                  Add on the fact that the park has nearly a dozen entrance
                  stations, and picking a location for your home base feels even
                  trickier. Whether you’re looking to explore the rocky Pacific
                  coastline, go forest bathing in the Hall of Mosses, or enjoy
                  the sounds of a rushing river, our picks for the best Olympic
                  National Park lodging have you covered. Below, 15 Airbnbs,
                  Vrbos.
                </p>
                <h3 class="blog-details-subtitle">
                  Solo Traveler Learns On The Road,
                </h3>
                <ul class="blog-details-feature-list">
                  <li>
                    You’ll use these concepts in whichever programming language
                    you learn in the future.
                  </li>
                  <li>
                    That way you have an overview before you start mastering a
                    dedicated language..
                  </li>
                  <li>Amazing Timing and Experience</li>
                </ul>
                <p>
                  Orem ipsum dolor sit &amp;, sdt consectetu adipiscing elit.
                  Aenean commodo ligula eget dolor. Cum socis Theme sed natoque
                  ut penatibus Etiam ultricies nisi vel augue. Cura bitur an
                  ultricies dictum felis eu pe de sit. Etiam rhoncus. Maecenas
                  tempus, tellus eget penatibus Rtiam.
                </p>
              </div>
            </div>
          </div>
          <div className="col-lg-4 col-md-6 col-sm-10">
            <div class="blog-sidebar ps-lg-4">
              <div class="blog-widget">
                <div class="sidebar-search">
                  <form>
                    <div class="form-inner">
                      <input type="text" placeholder="Search" />
                      <button type="submit">
                        <i class="bi bi-search"></i>
                      </button>
                    </div>
                  </form>
                </div>
              </div>
              <div class="blog-widget">
                <h4 class="blog-widget-title">Trending Stories</h4>
                <div class="trending-post">
                  <ul class="trending-post-list">
                    <li>
                      <div class="trending-post-single">
                        <div
                          class="package-image"
                          style={{
                            backgroundImage: `url(/image/blog-grid1.png)`,
                            height: '12vh',
                            width: '100%',
                            backgroundSize: 'cover',
                            backgroundPosition: 'center',
                          }}
                        ></div>
                        <div class="post-content">
                          <h6>
                            <a href="/blog-details">
                              The Most Underrated Europea Cities, According..
                            </a>
                          </h6>
                          <span class="post-date">September 8, 2022</span>
                        </div>
                      </div>
                    </li>
                    <li>
                      <div class="trending-post-single">
                      <div
                          class="package-image"
                          style={{
                            backgroundImage: `url(/image/blog-grid3.png)`,
                            height: '12vh',
                            width: '100%',
                            backgroundSize: 'cover',
                            backgroundPosition: 'center',
                          }}
                        ></div>
                        <div class="post-content">
                          <h6>
                            <a href="/blog-details">
                              The 25 Most Beautiful Beaches in Europe, From
                              Turkey.
                            </a>
                          </h6>
                          <span class="post-date">January 20, 2022</span>
                        </div>
                      </div>
                    </li>
                    <li>
                      <div class="trending-post-single">
                      <div
                          class="package-image"
                          style={{
                            backgroundImage: `url(/image/blog-grid3.png)`,
                            height: '12vh',
                            width: '100%',
                            backgroundSize: 'cover',
                            backgroundPosition: 'center',
                          }}
                        ></div>
                        <div class="post-content">
                          <h6>
                            <a href="/blog-details">
                              A Global Food of the World’s Best Restaurants.
                            </a>
                          </h6>
                          <span class="post-date">February 20, 2022</span>
                        </div>
                      </div>
                    </li>
                    <li>
                      <div class="trending-post-single">
                      <div
                          class="package-image"
                          style={{
                            backgroundImage: `url(/image/blog-grid2.png)`,
                            height: '12vh',
                            width: '100%',
                            backgroundSize: 'cover',
                            backgroundPosition: 'center',
                          }}
                        ></div>
                        <div class="post-content">
                          <h6>
                            <a href="/blog-details">
                              Hawaii Travel Restrictions Are Lifting to Know..
                            </a>
                          </h6>
                          <span class="post-date">October 08, 2022</span>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
             
              <div class="blog-widget">
                <div class="sidebar-social-area">
                  <h4 class="blog-widget-title">Follow us Astrip</h4>
                  <ul class="sidebar-social-list">
                    <li>
                      <a href="https://www.facebook.com/">
                        <i class="bi bi-facebook"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.twitter.com/">
                        <i class="bi bi-twitter"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.instagram.com/">
                        <i class="bi bi-instagram"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.pinterest.com/">
                        <i class="bi bi-pinterest"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            
            </div>
          </div>
        </div>
      </div>
      <Instagram></Instagram>
      <Footer></Footer>
    </>
  )
}

export default blog
